blocks: "false"
brackets:
  error: true
  expect: never
colons: never
colors: always
commaSpace: false
commentSpace:
  error: true
  expect: always
cssLiteral: never
customProperties:
  - c
  - caret
  - bgi
  - bg
  - b
  - bc
  - bb
  - bbc
  - bt
  - btc
  - bl
  - blc
  - br
  - brc
  - bb
  - bbc
  - by
  - byc
  - bx
  - bxc
  - r
  - m
  - mb
  - ml
  - mr
  - my
  - lh
  - p
  - px
  - py
  - pt
  - pb
  - po
  - s
  - o
  - a
  - tr
  - fn
  - fs
  - fw
  - td
  - sbc
  - sbw
  - size
depthLimit:
  error: true
  expect: 3
duplicates: true
efficient:
  error: true
  expect: always
exclude: false
extendPref:
  error: true
  expect: "@extend"
globalDupe: true
groupOutputByFile: true
ignoreFiles:
  - "./developer.styl"
indentPref:
  error: true
  expect: 2
leadingZero:
  error: true
  expect: always
maxErrors: false
maxWarnings: false
mixed: false
namingConvention: false
namingConventionStrict: false
noImportant: false
none:
  error: true
  expect: never
parenSpace:
  error: true
  expect: never
placeholders:
  error: true
  expect: always
prefixVarsWithDollar:
  error: true
  expect: always
quotePref:
  error: true
  expect: single
reporterOptions:
  columnSplitter: "  "
  columns:
    - lineData
    - severity
    - description
    - rule
  showHeaders: false
  truncate: true
semicolons:
  error: true
  expect: never
sortOrder:
  error: true
  expect: alphabetical
stackedProperties:
  error: true
  expect: never
trailingWhitespace:
  error: true
  expect: never
universal: false
valid: ""
zIndexNormalize: false
zeroUnits:
  error: true
  expect: never
